services:
  clickhouse1:
    image: clickhouse/clickhouse-server
    hostname: clickhouse1
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    volumes:
      - clickhouse_data1:/var/lib/clickhouse
      - clickhouse_data1:/var/log/clickhouse-server
      - type: bind
        source: ./config_1.xml
        target: /etc/clickhouse-server/config.xml

  clickhouse2:
    image: clickhouse/clickhouse-server
    hostname: clickhouse2
    ports:
      - "8003:9000"
      - "9124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    volumes:
      - clickhouse_data2:/var/lib/clickhouse
      - clickhouse_data2:/var/log/clickhouse-server
      - type: bind
        source: ./config_2.xml
        target: /etc/clickhouse-server/config.xml

volumes:
  clickhouse_data1:
  clickhouse_data2:

networks:
  ch_replicated:
    driver: bridge
