services:
  clickhouse:
    image: clickhouse/clickhouse-server
    hostname: ch-server
    # environment:
    # - CLICKHOUSE_CONFIG_FILE=/etc/clickhouse-server/config.xml
    # - CLICKHOUSE_USER=default
    # - CLICKHOUSE_PASSWORD=123456
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_data:/var/log/clickhouse-server
      - type: bind
        source: ./conf/single/users.xml
        target: /etc/clickhouse-server/users.xml
      - type: bind
        source: ./conf/single/config.xml
        target: /etc/clickhouse-server/config.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
