services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    hostname: zookeeper
    networks:
      - ch_replicated
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"

  clickhouse1:
    image: clickhouse/clickhouse-server
    hostname: clickhouse1
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper
    volumes:
      - type: bind
        source: config_1.xml
        target: /etc/clickhouse-server/config.xml

  clickhouse2:
    image: clickhouse/clickhouse-server
    hostname: clickhouse2
    ports:
      - "8003:9000"
      - "9124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper
    volumes:
      - type: bind
        source: config_2.xml
        target: /etc/clickhouse-server/config.xml

  clickhouse3:
    image: clickhouse/clickhouse-server
    hostname: clickhouse3
    ports:
      - "8004:9000"
      - "9125:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper
    volumes:
      - type: bind
        source: config_3.xml
        target: /etc/clickhouse-server/config.xml

  clickhouse4:
    image: clickhouse/clickhouse-server
    hostname: clickhouse4
    ports:
      - "8005:9000"
      - "9126:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper
    volumes:
      - type: bind
        source: config_4.xml
        target: /etc/clickhouse-server/config.xml

networks:
  ch_replicated:
    driver: bridge
